[package]
name = "frizz"
version = "0.1.0"
edition = "2018"
authors = ["{{authors}}"]

[lib]
name = "libfrizz"
crate-type = ["lib"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
select = "0.6.0-alpha.1"

[dev-dependencies]
serial_test = "*"

